#!/bin/bash
# Scans for phone connect to wifi and wakes up desktop
# Waits until at least 5 scans show phone is not connected before assuming we've truly disconnected

set -e # Abort on error
set -u # Abort on undeclared variable

BIN_DIR=$( dirname ${BASH_SOURCE[0]} )

max_disconnect_count=5
temp="$BIN_DIR"/.tmp/connected
connected=$( "$BIN_DIR"/is_phone_connected )
disconnect_count=$( cat "$temp" )
echo "phone is $connected and has been disconnected for $disconnect_count checks"
if [[ "$connected" = "connected" ]]; then
    if [[ $disconnect_count -ge $max_disconnect_count ]]; then
	"$BIN_DIR"/wake_desktop
    fi
    echo "0" > "$temp"
else
    new_disconnect_count=$(( $disconnect_count + 1 ))
    echo $(( $new_disconnect_count < $max_disconnect_count ? $new_disconnect_count : $max_disconnect_count )) > "$temp"
fi
