#!/usr/bin/python

import RPi.GPIO as GPIO
import time
from subprocess import call

pir_pin = 7
GPIO.setwarnings(False)
GPIO.setmode(GPIO.BOARD)
GPIO.setup(pir_pin, GPIO.IN)

last_wake = time.time()

def Motion(pir_pin):
	global last_wake
	hour = int(time.strftime("%H"))
	if (hour < 17 or hour > 23):
		print "not waking desktop, it is %s" % time.strftime("%H:%M")
		return
	now = time.time()
	diff = now - last_wake
	if diff > 900:
		print "waking desktop!"
		call(["/home/pi/scripts/wake_desktop"])
	else:
		print "not waking desktop, last wake time was only %s seconds ago" % diff
	last_wake = now

GPIO.add_event_detect(pir_pin, GPIO.RISING, callback=Motion)

while 1:
	time.sleep(100)
