#!/bin/bash
# Sends a wakeonlan packet to desktop

set -e # Abort on error
set -u # Abort on undeclared variable

# Send to entire subnet since shutdown desktop doesn't have an ip assigned yet
ipaddr=10.0.0.255
macaddr=D0:50:99:0E:32:20
wakeonlan -i "$ipaddr" "$macaddr"
